export const RECIPE_CALCULATOR_ACTIONS = {
  TOGGLE_GOODS_MODAL: '@RecipeCalculator/toggleGoodsModal' as const,
  UPDATE_RECIPE_NAME: '@RecipeCalculator/updateRecipeName' as const,
  UPDATE_GOODS_SEARCH_LIST: '@RecipeCalculator/updateGoodsSearchList' as const,
  SELECT_GOOD: '@RecipeCalculator/selectGood' as const,
  UNSELECT_GOOD: '@RecipeCalculator/unselectGood' as const,
  ADD_TO_RECIPE: '@RecipeCalculator/addToRecipe' as const,
  REMOVE_FROM_RECIPE: '@RecipeCalculator/removeFromRecipe' as const,
  RESTORE_GOOD: '@RecipeCalculator/restoreGood' as const,
  EDIT_QUANTITY: '@RecipeCalculator/editQuantity' as const,
  EDIT_COST: '@RecipeCalculator/editCost' as const,
  TOGGLE_CREATE_GOOD_MODAL: '@RecipeCalculator/toggleCreateGoodModal' as const,
  ADD_CREATED_GOOD_TO_RECIPE: '@RecipeCalculator/addCreatedGoodToRecipe' as const,
  TOGGLE_SEARCH_RECIPE_MODAL: '@RecipeCalculator/toggleSearchRecipeModal' as const,
  SELECT_RECIPE: '@RecipeCalculator/selectRecipe' as const,
  TOGGLE_EDIT_MODE: '@RecipeCalculator/toggleEditMode' as const,
  RESET_GOODS: '@RecipeCalculator/resetGoods' as const,
  RESET_COST: '@RecipeCalculator/resetCost' as const,
  RESET_QUANTITY: '@RecipeCalculator/resetQuantity' as const,
}
