export enum RecipeType {
  PLATTER = 'PLATTER',
  BARISTA_PREPARED_DRINK = 'BARISTA_PREPARED_DRINK',
  MADE_TO_SELL = 'MADE_TO_SELL',
  BOUGHT_TO_SELL = 'BOUGHT_TO_SELL',
  CAN_BE_DONATED_TO_CHARITY = 'CAN_BE_DONATED_TO_CHARITY',
  CARRY_OVER = 'CARRY_OVER',
}
